apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollive-db-pvc
  labels:
    app: ollive-inference-logger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
