apiVersion: v1
kind: Service
metadata:
  name: ollive-inference-logger-svc
  labels:
    app: ollive-inference-logger
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: ollive-inference-logger
